server:
  port: 8081
  tomcat:
    uri-encoding: UTF-8
    # ???? ?? ??
    relaxed-query-chars: '|,{,},[,],^,`,<,>,\,;,/,?,@,#,$,%,&,=,+'
    relaxed-path-chars: '|,{,},[,],^,`,<,>,\,;,/,?,@,#,$,%,&,=,+'

  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true


spring:
  config:
    import: optional:file:.env[.properties] # 환경변수 파일 로드

  datasource:
    url: jdbc:postgresql://localhost:5432/mydatabase
    username: myuser
    password: secret

  ai:
    vectorstore:
      pgvector:
        index-type: HNSW
        distance-type: COSINE_DISTANCE
        dimensions: 1536
        table-name : mall_vector  # movie_vector hotel_vector mall_vector
        initialize-schema: true
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: "gpt-4o"


upload:
  path: static/uploads

api:
  product:
    url: ${API_URL}