server:
  port: 8081
  tomcat:
    uri-encoding: UTF-8
    # ???? ?? ??
    relaxed-query-chars: '|,{,},[,],^,`,<,>,\,;,/,?,@,#,$,%,&,=,+'
    relaxed-path-chars: '|,{,},[,],^,`,<,>,\,;,/,?,@,#,$,%,&,=,+'

  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true


spring:
  config:
    import: optional:file:.env[.properties] # 환경변수 파일 로드

  datasource:
    url: jdbc:postgresql://localhost:5432/mydatabase
    username: myuser
    password: secret

  ai:
    vectorstore:
      pgvector:
        index-type: HNSW
        distance-type: COSINE_DISTANCE
        dimensions: 1536
        table-name : mall_vector  # movie_vector hotel_vector mall_vector
        initialize-schema: true
    openai:
      api-key: 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
      chat:
        options:
          model: "gpt-4o"


upload:
  path: src/main/resources/static/uploads/

api:
  product:
    url: http://localhost:8080